version: "3.9"
# Проверка командой
# curl -H "Content-Type: application/json" -H "Authorization: some-secret" -X GET localhost:81
# 
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx-go.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 81:80

  go:
    image: go-test:latest
    ports:
      - 8080:8080
    build:
      context: .

  unleash-proxy:
    image: unleashorg/unleash-proxy:latest
    environment:
      UNLEASH_PROXY_CLIENT_KEYS: "some-secret"
      # Прописать в hosts 127.0.0.1 myserver.ru
      # После запуска локально гитлаба, создать репу, содать feature flag
      # my_feature_name
      # Вытащить из меню Configure API_URL и InstanceID
      # Создать Strategies 50% , Environments: * и production
      UNLEASH_URL: "http://myserver.ru/api/v4/feature_flags/unleash/2"
      UNLEASH_API_TOKEN: "unleash"
      UNLEASH_INSTANCE_ID: "1xkiGQRGYtvfE5vSzWvm"
      UNLEASH_APP_NAME: "unleash-proxy"
    ports:
      - 3000:3000

  gitlab:
    image: gitlab/gitlab-ce:15.1.2-ce.0
    hostname: myserver.ru
    environment:
      GITLAB_HOME: /opt/gitlab
      GITLAB_OMNIBUS_CONFIG: "external_url 'http://myserver.ru/'; gitlab_rails['initial_root_password'] = '12345678'"
    volumes:
       # Перед запуском создать именованные вольюмы
       - gitlabdata:/opt/gitlab
       - gitlabdata2:/etc/gitlab
       - gitlabdata3:/var/opt/gitlab
    ports:
      - 80:80
    shm_size: '256m'

volumes:
  gitlabdata:
    external: true
  gitlabdata2:
    external: true
  gitlabdata3:
    external: true