version: "3.9"
services:
  muxy:
    image: mefellows/muxy:latest
    volumes:
      - ./muxy/config.yml:/opt/muxy/conf/config.yml
    ports:
      - 82:80

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/nginx-go.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  go:
    image: go-test:latest
    ports:
      - 8080:8080
    build:
      context: .

  unleash-proxy:
    image: unleashorg/unleash-proxy:latest
    environment:
      UNLEASH_PROXY_CLIENT_KEYS: "some-secret"
      UNLEASH_URL: "http://myserver.ru/api/v4/feature_flags/unleash/34"
      UNLEASH_API_TOKEN: "unleash"
      UNLEASH_INSTANCE_ID: "PzS-XXZB4gVvsMHdECTD"
      UNLEASH_APP_NAME: "unleash-proxy"
    ports:
      - 3000:3000

  unleash-proxy2:
    image: unleashorg/unleash-proxy:latest
    environment:
      UNLEASH_PROXY_CLIENT_KEYS: "some-secret"
      UNLEASH_URL: "http://myserver2.ru/api/v4/feature_flags/unleash/2"
      UNLEASH_API_TOKEN: "unleash"
      UNLEASH_INSTANCE_ID: "izTwyPdxKyMspgZLixvz"
      UNLEASH_APP_NAME: "unleash-proxy"
    ports:
      - 3001:3000

  unleash-proxy3:
    image: unleashorg/unleash-proxy:latest
    environment:
      UNLEASH_PROXY_CLIENT_KEYS: "some-secret"
      UNLEASH_URL: "http://myserver3.ru/api/v4/feature_flags/unleash/34"
      UNLEASH_API_TOKEN: "unleash"
      UNLEASH_INSTANCE_ID: "G7oZrt6mL3yQfwfU7_QE"
      UNLEASH_APP_NAME: "unleash-proxy"
    ports:
      - 3002:3000

  gitlab:
    image: gitlab/gitlab-ce:13.12.0-ce.0
    hostname: myserver.ru
    environment:
      GITLAB_HOME: /opt/gitlab
      GITLAB_OMNIBUS_CONFIG: "external_url 'http://myserver.ru/'; gitlab_rails['initial_root_password'] = '12345678'"
    volumes:
       # Перед запуском создать именованные вольюмы
       - gitlabdata:/opt/gitlab
       - gitlabdata2:/etc/gitlab
       - gitlabdata3:/var/opt/gitlab
    shm_size: '256m'
#    entrypoint: ["sleep", "infinity"]

#  gitlab2:
#    image: gitlab/gitlab-ce:15.1.2-ce.0
#    hostname: myserver2.ru
#    environment:
#      GITLAB_HOME: /opt/gitlab
#      GITLAB_OMNIBUS_CONFIG: "external_url 'http://myserver2.ru/'; gitlab_rails['initial_root_password'] = '12345678'"
#    volumes:
#       # Перед запуском создать именованные вольюмы
#       - gitlabdata4:/opt/gitlab
#       - gitlabdata5:/etc/gitlab
#       - gitlabdata6:/var/opt/gitlab
#    shm_size: '256m'
#    entrypoint: ["sleep", "infinity"]

  gitlab3:
    image: gitlab/gitlab-ce:14.10.0-ce.0
    hostname: myserver3.ru
    environment:
      GITLAB_HOME: /opt/gitlab
      GITLAB_OMNIBUS_CONFIG: "external_url 'http://myserver3.ru/'; gitlab_rails['initial_root_password'] = '12345678'"
    volumes:
       # Перед запуском создать именованные вольюмы
       - gitlabdata7:/opt/gitlab
       - gitlabdata8:/etc/gitlab
       - gitlabdata9:/var/opt/gitlab
    shm_size: '256m'
#    entrypoint: ["sleep", "infinity"]

volumes:
  gitlabdata:
    external: true
  gitlabdata2:
    external: true
  gitlabdata3:
    external: true
  gitlabdata4:
    external: true
  gitlabdata5:
    external: true
  gitlabdata6:
    external: true
  gitlabdata7:
    external: true
  gitlabdata8:
    external: true
  gitlabdata9:
    external: true